### ISSUE TITLE
Docker build - clojure access error

### ISSUE THREAD

**Issue by AlecRomine** [yetanalytics/datasim#29]
Greetings!
I cloned the code and tried to build with the provided build docker command.
I received this error: ```rg.eclipse.jgit.api.errors.TransportException: git@github.com:yetanalytics/project-pan.git: UnknownHostKey: github.com.```

I attempted these solutions:
[https://codehopper.nl/2018/09/27/clojure-gitlab-deps/](url) 
[https://medium.com/tokenmill/how-to-build-a-clojure-project-that-depends-on-private-git-repositories-in-docker-635c7a576726](url)
but there was no change to the error code.

Following this link: [https://stackoverflow.com/questions/13396534/unknownhostkey-exception-in-accessing-github-securely](url) 
I added ````StrictHostKeyChecking=no``` to ```~/.ssh/config```

and the error code changed to: ```Cloning: git@github.com:yetanalytics/project-pan.git
Error building classpath. git@github.com:yetanalytics/project-pan.git: Auth fail```

Any ideas of how to best proceed with build would be greatly appreciated.

**Comment by cliffcaseyyet** [comment]
Hi Alec,

This should now be resolved. We opened up the dep it was snagging on.

Thanks,
-Cliff
