### ISSUE TITLE
DATASIM Profile validation

### ISSUE THREAD

**Issue by FlorianTolk** [yetanalytics/datasim#56]
When a profile incorrectly forbids context activities in the templates using this rule

```
{
"location": "$.context.contextActivities",
"presence": "excluded"
}
```

No error is thrown, but it generates an empty array of statements. This should throw some form of error as this rule makes it impossible to send statements that comply to the profile.

**Comment by kelvinqian00** [comment]
Just to be clear, you're talking about templates where the rules/determining properties contradicting each other, right? For example:
```json
{"id" : "https://foo.org/template/bad",
 "rules" : [
    {
      "location": "$.context.contextActivities",
      "presence": "included"
    },
    {
      "location": "$.context.contextActivities",
      "presence": "excluded"
    }
  ]
}
```

**Comment by FlorianTolk** [comment]
Not quite,

In order to use an xAPI profile, all statements need to have the profile referenced in context.contextActivities. If you forbid these, then you can no longer use a profile.

This is one very weird rule, but it does break the profile spec and in turn causes errors in DATASIM.

**Comment by kelvinqian00** [comment]
Ok I see. Would it be possible to post a sample profile so I could reproduce the issue? When I tried to reproduce it, I was still able to generate statements, albeit ones without any contextActivity values.

**Comment by kelvinqian00** [comment]
To get a better idea of what I mean, if you replace all your templates with this:
```json
"templates":
[{"id":"https://example.org/excludeall",
  "type":"StatementTemplate",
  "inScheme":"https://example.org/bad",
  "prefLabel":{"en":"Exclude All"},
  "definition":{"en":"This Statement Templates excludes all components of a Statement"},
  "rules":[
    {"location":"$.id","presence":"excluded"},
    {"location":"$.timestamp","presence":"excluded"},
    {"location":"$.context","presence":"excluded"},
    {"location":"$.actor","presence":"excluded"},
    {"location":"$.verb","presence":"excluded"},
    {"location":"$.object","presence":"excluded"}]
}]
```
where everything, not just `context.contextActivities`, is excluded, then you will get a array of empty maps, _not_ an empty array.

**Comment by FlorianTolk** [comment]
This bug may have been fixed with the latest push then.

I was working with this version of a profile at the time
https://github.com/US-ELRR/Misc/blob/511891e07d5bd9df26f17ef887f786649c26c0f7/Objects/Level_1/ELRRProfile.json

Note this incorrect rule has already been removed (it was with this profile that I first encountered the error)

**Comment by kelvinqian00** [comment]
I tested that profile, both as-is and after adding back the `{"location": "$.context.contextActivity", "presence": "excluded"}` rule to each Statement Template, and I was still able to generate Statements. This is the first Statement from such a stream:
```json
{"id": "5eb56075-88f7-408d-a985-99404d940267",
 "actor": {
    "name": "Bob Fakename",
    "mbox": "mailto:bobfake@example.org"
 },
 "verb": {
    "id": "https://adlnet.gov/expapi/verbs/launched",
    "display": {"en": "launched"}
 },
 "object": {
    "id": "https://example.org/competency/113744736",
    "definition": {"type": "https://w3id.org/xapi/tla/activity-types/activity"},
    "objectType": "Activity"
 },
 "context": {
    "registration": "a3795ec8-54f3-499e-a4b1-4c067f3141d7"
 },
 "timestamp": "2019-11-18T11:42:05.191Z"
}
```
Notice the lack of a `contextActivity` value, but otherwise the Statement looks normal.

**Comment by FlorianTolk** [comment]
Guess it's not really an issue anymore then!
