### ISSUE TITLE
Recommendations for Standalone Deployment w/ UI?

### ISSUE THREAD

**Issue by vbhayden** [yetanalytics/datasim#71]
Morning team,

For an ideal simple deployment to support the upcoming TLA PlugFest, I'd like to avoid having weird ports exposed and preferably run on a single machine (some `datasim.tla.adlnet.gov`).  

We typically just stick everything into containers and route traffic through an nginx container, but that typically requires the containers having unique root paths for their requests etc.  With the API not allowing for a root path config option like `/api` and the containerized version having given us issues in the past, I'm curious what the best / recommended practice would be to get everything stood up without too much fuss etc.

Thanks!
-Trey

**Comment by milt** [comment]
Hey Trey,
Just to make sure, is it your intention to use the UI/API itself in the demo or do you just need to generate & send data?

If it's the former, we've got a PR+Branch with support for server env configuration (including a root path) here: https://github.com/yetanalytics/datasim/pull/72 . I'm currently looking at the UI to see if I need to add some config for the root path there too.

If it's just the latter you can run it "headless" a la the CLI, (the default entrypoint in the Dockerfile).

I also note we haven't yet published public docker builds of this, which I can remedy.

**Comment by milt** [comment]
For the UI, currently you will have to build it yourself if you want a different hostname/path to the server in the client, see [here](https://github.com/yetanalytics/datasim-ui#usage).

Basically the steps would be:
1. Edit the `datasim-ui.env/api` variable here to your desired host/port/path: https://github.com/yetanalytics/datasim-ui/blob/master/prod.cljs.edn#L1
2. Run `make clean gh-pages`
3. Serve the contents of the `gh-pages` directory that step 2 creates.

We plan on doing some kind of integrated CD for `datasim-ui` in the future, but it is currently manual.

**Comment by milt** [comment]
OK, #72 and #73 are merged, to set the root path you could do something like:

````shell
$ docker run -it \
> -e API_ROOT_PATH=/foo \
> -p 9090:9090 \
> --entrypoint bin/server.sh \
> yetanalytics/datasim:latest
[main] INFO com.yetanalytics.datasim.server - {:msg "Starting DATASIM API...", :root-path "/foo", :host "0.0.0.0", :port 9090, :allowed-origins ["https://yetanalytics.github.io" "http://localhost:9091"], :line 276}
[main] INFO org.eclipse.jetty.util.log - Logging initialized @6627ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 11.0.15+10-alpine-r1
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@320d98f5{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@1e954b94{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:9090}
[main] INFO org.eclipse.jetty.server.Server - Started @7051ms
````

And find that:

````shell
$ curl 0.0.0.0:9090/foo/health
OK%
````

Hope this helps!
